# Generated by Django 4.0.3 on 2022-03-19 06:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('op_blog', '0002_rename_tage_post_tag'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='tag',
            field=models.ManyToManyField(related_name='posts', to='op_blog.tag'),
        ),
    ]
