# Generated by Django 4.0.3 on 2022-03-19 06:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('op_blog', '0003_alter_post_tag'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='topic',
            field=models.CharField(choices=[('one piece', 'One Piece'), ('tech', 'tech'), ('programming', 'Programming')], max_length=15, null=True),
        ),
    ]
