# Generated by Django 4.0.3 on 2022-03-19 06:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('op_blog', '0004_post_topic'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='topic',
            field=models.CharField(choices=[('one piece', 'One Piece'), ('tech', 'Tech'), ('programming', 'Programming')], max_length=15, null=True),
        ),
    ]
