# Generated by Django 4.0.3 on 2022-03-19 19:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('op_blog', '0005_alter_post_topic'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='date',
            field=models.DateField(auto_now_add=True),
        ),
    ]
